version: '3'
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: somethingclever
      POSTGRES_USER: emailbot
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
  emailbot:
    depends_on:
      - postgres
    build: .
    volumes:
      - ".:/app"

volumes:
  database:
